### ISSUE TITLE
Add this to field/method access does not work

### ISSUE THREAD

**Issue by bickelmeister** [xdev-software/intellij-plugin-save-actions#10] opened 2023-06-23 10:54 UTC
## Environment 
IDEA: 
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1898M
Cores: 16
Registry:
    editor.focus.mode.color.light=5a5d63
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=5a5d63

Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.1.0)
    com.github.copilot (1.2.8.2631)
    Key Promoter X (2023.1.0)
    com.mallowigi (90.0.0)
    **software.xdev.saveactions (1.0.0)**
    CheckStyle-IDEA (5.80.1)
    org.sonarlint.idea (8.3.0.71062)
    com.chrisrm.idea.MaterialThemeUI (8.7.1)
    izhangzhihao.rainbow.brackets (2023.2.11)
    MavenRunHelper (4.23.222.2964.0)

Kotlin: 231-1.8.21-IJ9011.34

## Description

I am currently getting the following behaviour. As soon as I activate Save Actions and use it, the key word `this` is no longer added to fields/methods. Even existing ones are removed again.

## Expectation

The `this` key word is set were missing.

**Comment by AB-xdev** [comment] 2023-06-26 06:41
Thank you for your report @bickelmeister

Unfortunately I can't reproduce your problem:

https://github.com/xdev-software/intellij-plugin-save-actions/assets/45384811/81a555cc-d90d-4e51-8866-64d984694542

Can you maybe give more details?
Are there any IDE errors?

**Comment by bickelmeister** [comment] 2023-06-26 15:07
Some more screenshot. It is a bit tricky for me to make a video because the code is a bit confident. But may the screenshot will help. All red underlinded methods or variables have to be the `this.` in front. I can manually add them but after I press Strg+S it will be removed. If I deactivate the "Save Actions" it stays.
The mapper for example is initialized like this: 
`private final ***Mapper mapper;`

![grafik](https://github.com/xdev-software/intellij-plugin-save-actions/assets/35369684/9b90761f-3361-4337-9564-48986355b75a)

**Comment by AB-xdev** [comment] 2023-06-27 10:35
![grafik](https://github.com/xdev-software/intellij-plugin-save-actions/assets/45384811/db083337-7813-4f70-95ae-c7492238bdb1)

Uhm I think your settings are conflicting...

**Comment by bickelmeister** [comment] 2023-06-27 12:39
That makes me a little embarrassed now :D

**Comment by AB-xdev** [comment] 2023-06-27 13:17
Closing as fixed

**Closed by AB-xdev** 2023-06-27 13:17 UTC
